library(compiler)
parre=function(x){
  c=matrix(x,nrow=100,ncol=1)
  d=apply(c,1:2,fuck_final)
  print(mean(d))
  print(sqrt(var(d)))
  s=matrix(0,nrow=2,ncol=1)
  s[1,1]=mean(d)
  s[2,1]=sqrt(var(d))
  return(s)
}
parr=cmpfun(parre)